### PR TITLE
Add a system property for the lifetime timeout, similar to idle timeo…

### PR DESCRIPTION
**Pull request by angcap**
…ut and acquire timeout

Related to #1232

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@angcap Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1234)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1234) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@angcap Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1234)!

**Comment by angcap** [comment]
@violetagg ok, i try to add a test to PooledConnectionProviderTest.java

**Comment by violetagg** [comment]
@angcap I merged only the first commit (22f036309bbe6c4fc786485e40c11730423535b9) and then forward merge to master.
Thanks for the PR

**Pull request closed without merging**
