### PR TITLE
Added context propagation from caller thread/reactor context

### PR DESCRIPTION
**Pull request by violetagg**
Related to #1952

Co-authored-by: Marcin Grzejszczak <mgrzejszczak@vmware.com>

### CODE REVIEW

**Review by pderop — APPROVED** [review]
LGTM

**Comment by violetagg** [comment]
Rebased in order to pick up #2070 so that the build can pass.

**Comment by violetagg** [comment]
This PR is ready for a review
@reactor/netty-team PTAL

**Comment by violetagg** [comment]
The failed tests on CI are not related to this change.

**Review by pderop — APPROVED** [review]
LGTM

**Review by simonbasle — APPROVED** [review]

**Comment by violetagg** [comment]
@pderop @simonbasle Thanks for the review!

**Pull request merged**
