### PR TITLE
Feature/make javax.annotation optional

### PR DESCRIPTION
**Pull request by janvdbergh**
This fixes https://github.com/reactor/reactor-netty/issues/209.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@janvdbergh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=208)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-netty&pullRequestId=208) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@janvdbergh Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=208)!

**Comment by violetagg** [comment]
what do you think about adding also the fragment below?

```
  bundleImportPackages = ['!javax.annotation', '*']
```

**Comment by violetagg** [comment]
we can even remove also `com.fasterxml.jackson.*` as these packages are used only in tests.

```
  bundleImportPackages = ['!javax.annotation',
						  '!com.fasterxml.jackson.core',
						  '!com.fasterxml.jackson.databind',
						  '!com.fasterxml.jackson.module',
						  '*']
```

**Comment by janvdbergh** [comment]
Removing these packages is an excellent idea, and I updated the pull request.
I have verified that this starts up fine in our OSGi container.

**Comment by violetagg** [comment]
Closed via 507d29db2253c5f48f9a59a9ddaf4537f29c7619 and 64835df6e531ecd0b07ebbbe2f958d561429ef14

**Pull request closed without merging**
