### PR TITLE
Fix typo in javadoc for `allowPartialChunks` setting

### PR DESCRIPTION
**Pull request by andrross**
FYI @reta, I stumbled across a typo in #3453

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Review by violetagg — APPROVED** [review]
@andrross Thanks for the PR!
Can you please sing the CLA?
May be we can mark this as on obvious fix? https://cla.pivotal.io/about#obvious-fix

**Comment by andrross** [comment]
@pivotal-cla This is an Obvious Fix

**Comment by violetagg** [comment]
@andrross @reta I back ported the fix to 1.1.x branch

**Comment by reta** [comment]
> @andrross @reta I back ported the fix to 1.1.x branch

Thanks a lot!

**Pull request merged**
