### PR TITLE
Add API for configuring a custom HostsFileEntriesResolver

### LINKED ISSUE #1822: Turn off netty client DNS connect retry.
Turn off netty client DNS connect retry.

[StackOverflow](https://stackoverflow.com/questions/69218709/how-can-i-turn-off-netty-client-dns-connect-retry?noredirect=1#comment122351702_69218709)

## Motivation

I'm using Netty-httpClient for Spring webClient.

When I connect  `www.naver.com` and set the host like this.

```
127.0.0.1 www.naver.com
125.209.222.142 www.naver.com
```
And run httpClient.get() result like this.

```
 DEBUG r.n.r.PooledConnectionProvider - [id:83c8069f] Created a new pooled channel, now: 0 active connections, 0 inactive connections and 0 pending acquire requests.
 DEBUG r.n.t.SslProvider - [id:83c8069f] SSL enabled using engine sun.security.ssl.SSLEngineImpl@5412b204 and SNI www.naver.com:443
 DEBUG i.n.b.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
 DEBUG i.n.b.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
 DEBUG i.n.u.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@7ec1e7a5
 DEBUG r.n.t.TransportConfig - [id:83c8069f] Initialized pipeline DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.sslReader = reactor.netty.tcp.SslProvider$SslReadHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
 INFO  reactor - [id:83c8069f] REGISTERED
 DEBUG r.n.t.TransportConnector - [id:83c8069f] Connecting to [www.naver.com/127.0.0.1:443].
 INFO  reactor - [id:83c8069f] CONNECT: www.naver.com/127.0.0.1:443
 INFO  reactor - [id:83c8069f] CLOSE
 DEBUG r.n.t.TransportConnector - [id:83c8069f] Connect attempt to [www.naver.com/127.0.0.1:443] failed.
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: www.naver.com/127.0.0.1:443
Caused by: java.net.ConnectException: Connection refused: no further information
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
    at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
 DEBUG r.n.r.PooledConnectionProvider - [id:0e3c272c] Created a new pooled channel, now: 0 active connections, 0 inactive connections and 0 pending acquire requests.
 DEBUG r.n.t.SslProvider - [id:0e3c272c] SSL enabled using engine sun.security.ssl.SSLEngineImpl@47b241b and SNI www.naver.com:443
 DEBUG r.n.t.TransportConfig - [id:0e3c272c] Initialized pipeline DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.sslReader = reactor.netty.tcp.SslProvider$SslReadHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
 INFO  reactor - [id:0e3c272c] REGISTERED
 INFO  reactor - [id:83c8069f] UNREGISTERED
 DEBUG r.n.t.TransportConnector - [id:0e3c272c] Connecting to [www.naver.com/125.209.222.142:443].
 INFO  reactor - [id:0e3c272c] CONNECT: www.naver.com/125.209.222.142:443
 DEBUG r.n.r.DefaultPooledConnectionProvider - [id:0e3c272c, L:/192.168.55.77:52910 - R:www.naver.com/125.209.222.142:443] Registering pool release on close event for channel
 DEBUG r.n.r.PooledConnectionProvider - [id:0e3c272c, L:/192.168.55.77:52910 - R:www.naver.com/125.209.222.142:443] Channel connected, now: 1 active connections, 0 inactive connections and 0 pending acquire requests.
 DEBUG i.n.u.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
 DEBUG i.n.u.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
 DEBUG i.n.u.Recycler - -Dio.netty.recycler.linkCapacity: 16
 DEBUG i.n.u.Recycler - -Dio.netty.recycler.ratio: 8
 DEBUG i.n.u.Recycler - -Dio.netty.recycler.delayedQueue.ratio: 8
 INFO  reactor - [id:0e3c272c, L:/192.168.55.77:52910 - R:www.naver.com/125.209.222.142:443] ACTIVE
```

see that. I don't want connect twice and don't spend more time to connect.
just fail if can not make connect.

## Desired solution

Configure DNS resolve timeout and requestTimeout include this if possible.

### PR DESCRIPTION
**Pull request by violetagg**
Fixes #1822

### CODE REVIEW

**Comment by simonbasle** [comment]
I was confused for a bit by Netty's `DefaultHostsFileEntriesResolver` having an `adresses` method. The `DnsNameResolver` using `HostsFileEntriesResolver` does check if it is the default instance in which case it returns the whole list, while user-provided resolvers can only return a single address...

`DefaultHostsFileEntriesResolver` is final, and thus can't be extended by users.

That's a bummer, but a limitation of the Netty API.

Note that in the provided example in comment above, the `resolvedAddressTypes` is ignored.
An alternative code doing the same but honoring the type could easily be done using `DefaultHostsFileEntriesResolver:

```java
DefaultHostsFileEntriesResolver defaultResolver = new DefaultHostsFileEntriesResolver();
List<InetAddress> addresses = defaultResolver.addresses(inetHost, resolvedAddressTypes);
return addresses != null && !addresses.isEmpty() ? addresses.get(0) : null;
```

**Comment by simonbasle** [comment]
So this actually fixes the issue because the `DnsNameResolver` won't see a `DefaultHostsFileEntriesResolver` and thus won't return multiple addresses for the purpose of `resolveAll`  👍

**Review by simonbasle — APPROVED** [review]
> `DnsNameResolver` using `HostsFileEntriesResolver` does check if it is the default instance in which case it returns the whole list, while user-provided resolvers can only return a single address...

I wonder: should this and the snippet you provided (or my edit) be mentioned in the reference doc @violetagg ?

**Comment by violetagg** [comment]
> I wonder: should this and the snippet you provided (or my edit) be mentioned in the reference doc @violetagg ?

This is a rare case and for the moment I do not intend to provide an example in the ref documentation.

**Comment by KimJejun** [comment]
@violetagg Thanks. I will try this when released

**Pull request merged**
