### PR TITLE
Added invoking parent.drain if future/promise exists

### PR DESCRIPTION
**Pull request by segabriel**
Closes: #546

### CODE REVIEW

**Comment by segabriel** [comment]
For now, the following test is not passed:
```
reactor.netty.http.server.HttpSendFileTests > sendFileAsync4096Negative FAILED
    org.junit.ComparisonFailure: expected:<[101, 114, 114, 111, 114]> but was:<null>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at reactor.netty.http.server.HttpSendFileTests.doTestSendFileAsync(HttpSendFileTests.java:345)
        at reactor.netty.http.server.HttpSendFileTests.sendFileAsync4096Negative(HttpSendFileTests.java:290)
```

but in the master branch, it's not passed too.

**Comment by violetagg** [comment]
@segabriel Rebase on top the latest changes. Let's see whether this time the test will pass.
Regards,
Violeta

**Comment by segabriel** [comment]
@violetagg done, but the test is still as the failed one.

**Comment by violetagg** [comment]
@segabriel Try again (I made some changes)

**Comment by smaldini** [comment]
I am still wondering, the fix itself is correct but do we want to have this behavior ? Shouldn't we close on first error and not try to pull more publisher ?
In the issue it is mentioned that you dispose processor, which creates a cancellation exception. Have you tried just onComplete the processor instead ?

**Comment by segabriel** [comment]
@smaldini 
> In the issue it is mentioned that you dispose processor, which creates a cancellation exception. Have you tried just onComplete the processor instead ?

yes I tried and `onComplete` has the same behavior as `dispose`. 

> do we want to have this behavior ?

In my opinion yes, because we do it in other cases, for example, when we emit no message and immediately close the publisher. Or we have set `.timeout(Duration)` and we have no result it will invoke `close`.

**Comment by smaldini** [comment]
Will close for now - #546 should be closed once we document an alternative but we already are planning to not have such queue for publishers anymore in the next major version.

**Pull request closed without merging**
