### PR TITLE
fix #1194 Ensure custom HOST header is preserved when websocket

### LINKED ISSUE #1194: HttpClient with websocket can not pass Host Header since 0.9.7
## Expected Behavior
httpClient pass Host Header to Sever
## Actual Behavior
httpClient lost Host Header since 0.9.7
## Steps to Reproduce

```java
 @Test(timeout = 10000)
  public void test() {
    DisposableServer disposableServer =
        HttpServer.create()
            .port(9999)
            .handle(
                (req, resp) -> {
                  String host = req.requestHeaders().get("Host");
                  if (host.equals("test.com")) { // Test Host
                    return resp.sendWebsocket(
                        (i, o) -> {
                          return o.sendClose();
                        });
                  } else {
                    return resp.status(404);
                  }
                })
            .bindNow();

    HttpClient httpClient = HttpClient.create();
    httpClient
        .headers(
            entries -> {
              entries.add("Host", "test.com");
              entries.add("aa", "bb");
            })
        .baseUrl("http://localhost:" + disposableServer.port())
        .websocket()
        .connect()
        .block();
  }

```
Run the test with 0.9.6.RELEASE, Test pass. But run the test with 0.9.7.RELEASE, Test failed!
## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`):
* OS and version (eg `uname -a`):

### PR DESCRIPTION
**Pull request by violetagg**
This fix is in addition to PR#1047
Fixes #1194

### CODE REVIEW

**Comment by violetagg** [comment]
@gongmingbin @Unthrottled @simonbasle PTAL

**Comment by Unthrottled** [comment]
@violetagg 

I tested these changes against the issue that spawned #1047 , and that issue re-appears in branch.

I have a [demo project](https://github.com/QDivision/external-websocket-error-sample) if you want to take a look for yourself (you should use this [gateway project](https://github.com/QDivision/external-websocket-error-sample/tree/master/working-external-websocket))

When I try to establish a connection I [get this in the logs](https://pastebin.com/ZNpLi9vu) and the websocket connection fails. 

When I built this feature branch I used these properties:

```
reactorPoolVersion=0.1.5.RELEASE
version=0.9.10.websocketz
reactorCoreVersion=3.3.7.RELEASE
compatibleVersion=0.9.9.RELEASE
```

Just for fun I also tested something out when I was on the same branch, with almost the same properties (I changed `version` property to avoid collisions). 

When I added the host header removal back, I was able to establish a websocket connection and send messages. :thinking:  

Here are the [logs with the successful connection](https://pastebin.com/XN5xZzb7)

**Comment by Unthrottled** [comment]
I did a little packet sniffing and found somethings (I don't know if will help)

Here is what the successful websocket request/response looks like (the code with the host header removal):

```
GET / HTTP/1.1
Pragma: no-cache
Origin: http://localhost:8870
Accept-Language: en-US,en;q=0.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36 OPR/67.0.3575.53
Cache-Control: no-cache
Forwarded: proto=http;host="localhost:8870";for="127.0.0.1:44756"
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
X-Forwarded-Prefix: /websocket/echo
X-Forwarded-Port: 8870
X-Forwarded-Host: localhost:8870
accept: */*
host: echo.websocket.org
upgrade: websocket
connection: upgrade
sec-websocket-key: iX+J/RUEsCwA/gbRQmx6cg==
sec-websocket-version: 13

HTTP/1.1 101 Web Socket Protocol Handshake
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: content-type
Access-Control-Allow-Headers: authorization
Access-Control-Allow-Headers: x-websocket-extensions
Access-Control-Allow-Headers: x-websocket-version
Access-Control-Allow-Headers: x-websocket-protocol
Access-Control-Allow-Origin: http://localhost:8870
Connection: Upgrade
Date: Mon, 06 Jul 2020 17:30:18 GMT
Sec-WebSocket-Accept: cezLjMzOoREhAJ9v0lw5iiWObxg=
Server: Kaazing Gateway
Upgrade: websocket
```

Here is the exact same request with out the host header removal code in this branch

```
GET / HTTP/1.1
Pragma: no-cache
Origin: http://localhost:8870
Accept-Language: en-US,en;q=0.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36 OPR/67.0.3575.53
Cache-Control: no-cache
Host: localhost:8870
Forwarded: proto=http;host="localhost:8870";for="127.0.0.1:44722"
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
X-Forwarded-Prefix: /websocket/echo
X-Forwarded-Port: 8870
X-Forwarded-Host: localhost:8870
accept: */*
upgrade: websocket
connection: upgrade
sec-websocket-key: 7Pn3V9z+n1AvZrbHkOgLtw==
sec-websocket-version: 13

HTTP/1.1 404 Not Found
Content-Type: text/html
Content-Length: 61

<html><head></head><body><h1>404 Not Found</h1></body></html>
```

**Comment by Unthrottled** [comment]
`host: echo.websocket.org` !== `Host: localhost:8870`

So the requests are made to a gateway running on `localhost:8870` which proxies the websocket request to the external service. It looks like the external service is expecting the host to be `echo.websocket.org`. Is that the standard expectation? (That feels right)

**Comment by violetagg** [comment]
@Unthrottled I think that your original problem is more related to an issue in Spring Gateway.
When it is HTTP, Spring Gateway removes the HOST header except when there is configuration to not remove it.

https://github.com/spring-cloud/spring-cloud-gateway/blob/3d76da7240acb80cfe5c14e69d3a1624f25d0d8b/spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/NettyRoutingFilter.java#L135-L139

While when it is WebSocket the HOST header is not removed.

https://github.com/spring-cloud/spring-cloud-gateway/blob/master/spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/WebsocketRoutingFilter.java

So my proposal is to revert the change that we made in Reactor Netty and open an issue in Spring Gateway.

Wdyt?

**Comment by gongmingbin** [comment]
That is work for me. @violetagg

**Comment by Unthrottled** [comment]
> So my proposal is to revert the change that we made in Reactor Netty and open an issue in Spring Gateway.

@violetagg That sounds good! Just as long as the issue get's fixed. 

Did you want me to an issue in Spring Cloud gateway?

**Comment by violetagg** [comment]
> > So my proposal is to revert the change that we made in Reactor Netty and open an issue in Spring Gateway.
> 
> @violetagg That sounds good! Just as long as the issue get's fixed.
> 
> Did you want me to an issue in Spring Cloud gateway?

Yes please

I'll close this PR and revert the change that we made in 0.9.7 release

OK?

**Comment by Unthrottled** [comment]
@violetagg Sounds like a plan! Thanks for the help with this!

**Comment by violetagg** [comment]
OK thanks.
Let me close this one as we will NOT proceed with this change.

**Pull request closed without merging**
