### PR TITLE
Deal with extremely long header values

### LINKED ISSUE #1584: A really large header should not result in a client PrematureCloseException
If the header value is longer than the configured maximum header length and not 'extremely' long, then the customer gets a 413.  However, if the header value is 'extremely' long, the user experiences a severed connection while sending the request.

## Expected Behavior

Within reason, all 'too long' header values should result in a 413 Response.

## Actual Behavior

When the header is really long, the code will sever the connection before it finishes reading the request.

## Steps to Reproduce

```
	@ParameterizedTest
	@ValueSource(ints = {1_000, 1_000_000})
	void testHeaderTooLong(final int headerSize) {
		final String path = "/";
		final DisposableServer server = HttpServer.create()
				.port(0)
				.httpRequestDecoder(c -> c.maxHeaderSize(100))
				.route(routes ->
					routes.get(path, (req, resp) -> resp.sendString(Mono.just("oh nos!")))
				).bindNow();

		final String headerVal =
				IntStream
						.range(0, headerSize)
						.mapToObj(i -> "a")
						.collect(Collectors.joining());

		final HttpClient client = createClient(server.port());

		final int status = client.headers(hs -> hs.add("longheader", headerVal))
				.get()
				.uri(path)
				.response()
				.map(resp -> resp.status().code())
				.block();

		assertThat(status).isEqualTo(413);
		server.disposeNow();
	}
```

## Possible Solution

I will follow this up with a link to a branch that has the failing test and a 'feels hackish' fix.  I'm pretty certain you'll want to go another route:)

Minimally, I'm guessing [this code](https://github.com/reactor/reactor-netty/blob/d21d5146258ae5966deb16b9ecbf19d2920153eb/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java#L672) will need to change.

## Your Environment

mac laptop, many environments

* Reactor version(s) used: 1.0.5, master
* Other relevant libraries versions (eg. `netty`, ...): 
* JVM version (`java -version`): several..
* OS and version (eg. `uname -a`): several..

### PR DESCRIPTION
**Pull request by crankydillo**
You could consider taking the test. I certainly have no problems if you burn the prod code down:) However, if you'd like me to work on a solution, please consider dropping comments below. I can't guarantee I can work on this, but I may be able to squeeze out some time.

Fixes #1584

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@crankydillo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1586)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1586) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by violetagg** [comment]
@crankydillo Please sign the CLA

**Comment by crankydillo** [comment]
I must admit that I didn't run all the tests:( It looks like this change breaks some of them. I'm glad I opened this as a draft! Anyhow, take what you want. If you don't have time to work on it, let me know. I'm slowly getting an understanding of the code.

**Comment by violetagg** [comment]
I should admit that I cannot reproduce it on Mac OS, what OS do you use?

**Comment by crankydillo** [comment]
> I should admit that I cannot reproduce it on Mac OS, what OS do you use?

```
$ uname -a
Darwin REMOVED 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; REMOVED:REMOVED/RELEASE_X86_64 x86_64
```

```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-macosx) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-macosx) (build 25.212-b04, mixed mode)
```

**Comment by violetagg** [comment]
https://github.com/reactor/reactor-netty/issues/1584#issuecomment-899453251

**Pull request closed without merging**
