### PR TITLE
Ensure the custom Netty handlers are able to access tracing information

### PR DESCRIPTION
**Pull request by violetagg**
Related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1690

### CODE REVIEW

**Comment by violetagg** [comment]
@marcingrzejszczak PTAL

**Comment by violetagg** [comment]
@reactor/netty-team Please wait with the review I need to resolve the flaky test.

**Review by OlegDokuka — APPROVED** [review]
LGTM

**Comment by violetagg** [comment]
@OlegDokuka Thanks for the review!

**Pull request merged**
