### PR TITLE
BufferFlux and BufferMono do not depend on netty-codec-http anymore

### PR DESCRIPTION
**Pull request by violetagg**
Add API for providing a function for extracting a Buffer from an Object

Related to #1953

### CODE REVIEW

**Review by pderop — APPROVED** [review]
LGTM

**Comment by violetagg** [comment]
@pderop I simplified the change. Can you take a look again?

**Review by pderop — APPROVED** [review]
looking good

**Comment by violetagg** [comment]
@pderop Thanks

**Pull request merged**
