### PR TITLE
When `HttpOperations#afterMarkSentHeaders` throws an error in `HttpOperations#sendObject`, ensure the `ByteBuf` is released just once

### PR DESCRIPTION
**Pull request by violetagg**

### CODE REVIEW

**Comment by violetagg** [comment]
Failed tests on Mac OS CI are not related

**Review by pderop — APPROVED** [review]
seems good to me.

notice that when reverting the patch from HttpOperations.java, then the tests seem to pass OK anyway.

**Comment by violetagg** [comment]
@pderop I extended the test, please check again!

**Comment by violetagg** [comment]
@pderop Thanks for the review!

**Pull request merged**
