### PR TITLE
Publish docs to spring.io

### PR DESCRIPTION
**Pull request by pderop**
This is a new attempt to publish javadoc and reference docs to docs.spring.io/projecrtreactor/reactor-netty/

in previous abandonned PR #3328 , the PR was based on publishing an additional docs.zip with special properties, but this introduced important drawbacks:

- an additional apidocs-zip classifier was added, meaning a new artifact to be pushed to artifactory & central
- the docs publications were delayed (because autorepo scripts are based on cron jobs)
- same for symlink generation, the autoln scripts are based on cron jobs)

in this PR, a new approach similar to [spring-security deployDocs](https://github.com/spring-projects/spring-security/blob/main/buildSrc/src/main/groovy/io/spring/gradle/convention/DeployDocsPlugin.groovy#L54-L80) task is used: docs are now published instantly using some ssh commands (and autoln scripts are also executed using ssh). 

So, no more delays, instant publication, and no more additional special docs zip published.

please notice the following:

- a new docs/build.gradle has been added, but it must be run with a JDK compatible with JAVA 11, because the PR uses org.hidetake.ssh gradle plugin which requires java 11 +
- because setup.gradle has been updated, I got trouble with spotless which could not parse the license headers from setup.gradle. After some researches, it turns out that I had to update the regex in build.gradle for the spotless task, and I did that same that has been done in the #2899 , in [build.gradle](https://github.com/reactor/reactor-netty/pull/2899/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7). 

on each push, the following docs will be updated here:

`https://docs.spring.io/projectreactor/reactor-netty/docs/VERSION/api/` (javadoc)
`https://docs.spring.io/projectreactor/reactor-netty/docs/VERSION/reference/html/` (reference doc)
`https://docs.spring.io/projectreactor/reactor-netty/docs/VERSION/reference/pdf/` (pdf reference doc)
`https://docs.spring.io/projectreactor/reactor-netty/docs/current` -> (the latest stable docs)
`https://docs.spring.io/projectreactor/reactor-netty/docs/current-SNAPSHOT` -> (the most recent snapshot docs)
`https://docs.spring.io/projectreactor/reactor-netty/docs/<major>.<minor>.x` -> (the most recently released version starting with `<major>.<minor>`)
`https://docs.spring.io/projectreactor/reactor-netty/docs/<major>.<minor>.x-SNAPSHOT` -> (the most recent snapshot docs starting with `<major>.<minor>`)

you can check existing docs which have been manually uploaded in https://docs.spring.io/projectreactor/reactor-netty/docs/

### CODE REVIEW

**Comment by pderop** [comment]
mmm, let me fix some spotless checks before reviewing ... will do this in a few moment ...

**Comment by pderop** [comment]
@violetagg , it should be ok to review now; did my best to test this PR using a simulated environment ...
let me know.

**Comment by violetagg** [comment]
Let's make a PR against 1.1.x branch instead of 1.0.x branch.
Can we find a way to not switch back and forth the java version?

**Comment by pderop** [comment]
> Can we find a way to not switch back and forth the java version?

I'l precisely working on this topic currently.

**Comment by pderop** [comment]
I'm closing this PR, and will recreate a new one for 1.1.x (and will update this closed one to say it's superseded by the other one).

**Comment by pderop** [comment]
This is superseded by https://github.com/reactor/reactor-netty/pull/3345

**Pull request closed without merging**
