### PR TITLE
Update Micrometer dependency to version 2.0.0-M2

### PR DESCRIPTION
**Pull request by violetagg**
Update Reactor Netty to use micrometer-api.

Related to #1952

### CODE REVIEW

**Review by pderop — CHANGES_REQUESTED** [review]
nit: please update the Copyright year in the following files:

- build.gradle
- reactor-netty/build.gradle
- reactor-netty-core/build.gradle
- reactor-netty-examples/build.gradle
- reactor-netty-http/build.gradle
- reactor-netty-incubator-quic/build.gradle

**Comment by violetagg** [comment]
> nit: please update the Copyright year in the following files:
> 
> * build.gradle
> * reactor-netty/build.gradle
> * reactor-netty-core/build.gradle
> * reactor-netty-examples/build.gradle
> * reactor-netty-http/build.gradle

Interesting - need to check why spotless does not complain ...

**Comment by simonbasle** [comment]
> Interesting - need to check why spotless does not complain ...

the tool is currently only configured to look at .java files

**Comment by violetagg** [comment]
I rebased in order to pickup the changed in the build.gradle files. PTAL

**Review by pderop — APPROVED** [review]
LGTM

**Review by simonbasle — COMMENTED** [review]
LGTM

**Review by simonbasle — APPROVED** [review]

**Pull request merged**
