### PR TITLE
Issue-1673: Use non language specific test conditions

### PR DESCRIPTION
**Pull request by roggenbrot**
Original issue: #1673

This PR fixes the failed test cases on env language != en

### CODE REVIEW

**Review by violetagg — APPROVED** [review]

**Comment by violetagg** [comment]
@reactor/netty-team PTAL

**Comment by roggenbrot** [comment]
Maybe a new github action `build (ubuntu-20.04 Locale)` that includes all locales (RUN apt-get install -y locales locales-all) and is started with a random locale would make sense to prevent language specific problems in the future

**Comment by violetagg** [comment]
> Maybe a new github action `build (ubuntu-20.04 Locale)` that includes all locales (RUN apt-get install -y locales locales-all) and is started with a random locale would make sense to prevent language specific problems in the future

Would you like to provide PR with let say a job that will run once a week?

**Comment by roggenbrot** [comment]
I'll have a look what I can do

**Review by simonbasle — APPROVED** [review]

**Comment by violetagg** [comment]
@roggenbrot Thanks for the PR!

**Pull request merged**
