### PR TITLE
#1257 Target host should not be resolved when proxy is configured

### PR DESCRIPTION
**Pull request by anilgursel**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@anilgursel Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1258)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1258) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by violetagg** [comment]
@anilgursel Please sign the CLA

**Comment by pivotal-issuemaster** [comment]
@anilgursel Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1258)!

**Comment by anilgursel** [comment]
@violetagg I believe the problem is caused because `HttpClientConfig` is not immutable (actually its parent `ClientTransportConfig`).  When a modification is done the configuration change affects all others that inherited the same config.  `duplicate()` is only doing a shallow copy.  Refactoring it to make a deep copy might be expensive at runtime.  I wonder if we should consider using copy-on-write for each field.  I am afraid this may require some major refactoring.  If you have any suggestions without requiring major changes, please let me know.

**Comment by violetagg** [comment]
@anilgursel I merged to master only the test (with `@Ignore`) from the PR for 0.9.x branch

**Comment by violetagg** [comment]
> @violetagg I believe the problem is caused because `HttpClientConfig` is not immutable (actually its parent `ClientTransportConfig`). When a modification is done the configuration change affects all others that inherited the same config. `duplicate()` is only doing a shallow copy.

Yes this is deliberate

> Refactoring it to make a deep copy might be expensive at runtime. I wonder if we should consider using copy-on-write for each field. I am afraid this may require some major refactoring. If you have any suggestions without requiring major changes, please let me know.

@anilgursel PTAL #1264

**Comment by violetagg** [comment]
The PR is superseded by #1264

**Pull request closed without merging**
