### PR TITLE
Adapt to the new EventLoop API for checking the channel compatibility

### LINKED ISSUE #2291: Enable the check for the type of the executor
This is related to #2290

### PR DESCRIPTION
**Pull request by violetagg**
Fixes #2291

### CODE REVIEW

**Comment by pderop** [comment]
should we ignore the CI checks errors ?

**Comment by violetagg** [comment]
No I need to check why the UDS tests are failing

**Review by pderop — APPROVED** [review]
LGTM

**Comment by pderop** [comment]
ignore my last LGTM, sorry, that was a mistake :blush:. Will review again after tests have passed. 



<br class="Apple-interchange-newline">

**Comment by violetagg** [comment]
@pderop I created an issue for `HttpMetricsHandlerTests > testServerConnectionsRecorder` as I observe this test to fail on all versions from time to time.
I do not consider it related to this change.

**Review by pderop — APPROVED** [review]
looks good to me.

**Comment by violetagg** [comment]
@pderop Thanks

**Comment by violetagg** [comment]
Related to #1873

**Pull request merged**
