### PR TITLE
[test] Ensure the access log was written

### LINKED ISSUE #2373: Stabilize HttpProtocolsTests.testAccessLog
This test is flaky and it is observed that it fails from time to time on the CI fo version 2.0.x

Observed error:

```
HttpProtocolsTests > testAccessLog(HttpServer, HttpClient) > reactor.netty.http.HttpProtocolsTests.testAccessLog(HttpServer, HttpClient)[1] FAILED
    Wanted but not invoked:
    appender.doAppend(<Capturing argument>);
    -> at reactor.netty.http.HttpProtocolsTests.testAccessLog(HttpProtocolsTests.java:370)
    Actually, there were zero interactions with this mock.
        at app//reactor.netty.http.HttpProtocolsTests.testAccessLog(HttpProtocolsTests.java:370)
```

### PR DESCRIPTION
**Pull request by violetagg**
Use `ListAppender` instead of mocking.

Fixes #2373

### CODE REVIEW

**Comment by pderop** [comment]
some tests are still failing, not sure, but maybe the testAccessLog timeout should also be increased (currently, 5 seconds is used):

```
			client.port(disposableServer.port())
			      .get()
			      .uri("/")
			      .responseSingle((res, bytes) -> {
			          protocol.set(res.responseHeaders().get("x-http2-stream-id") != null ? "2.0" : "1.1");
			          return Mono.just(res.responseHeaders().get(NettyPipeline.AccessLogHandler));
			      })
			      .as(StepVerifier::create)
			      .expectNext("FOUND")
			      .expectComplete()
			      .verify(Duration.ofSeconds(5));
```

**Comment by pderop** [comment]
forget my last comment, it does not make sense, because if a timeout exception occurs, then we would see  it in the logs.

**Comment by violetagg** [comment]
Wait with the review the new util is behaving strange...

**Comment by violetagg** [comment]
This is superseded by #2447

**Pull request closed without merging**
