### PR TITLE
Update http-client-conn-provider.adoc

### PR DESCRIPTION
**Pull request by PyAntony**
Added a note to give more clarity to the usage of `maxConnections`.

### CODE REVIEW

**Comment by PyAntony** [comment]
See #2052.

**Review by violetagg — APPROVED** [review]

**Comment by violetagg** [comment]
@reactor/netty-team PTAL

**Review by pderop — APPROVED** [review]
LGTM

**Review by simonbasle — APPROVED** [review]

**Comment by violetagg** [comment]
@PyAntony Thanks for the PR!
I committed it to `1.0.x` branch with 546a749 and then merged it to `main` branch with 06532a2

**Comment by PyAntony** [comment]
thank you!

**Pull request closed without merging**
