### PR TITLE
multiple binds and shared handler lambda

### PR DESCRIPTION
**Pull request by simonbasle**
see #67.

### CODE REVIEW

**Comment by simonbasle** [comment]
cc @bclozel. This is early stage prototyping and toying around, see `HttpMultiServerTest` for 2 alternative APIs.

**Comment by simonbasle** [comment]
@smaldini any feedback on that? is it overlapping with your current API rework?

**Comment by smaldini** [comment]
Will rework atop 0.8

**Comment by bclozel** [comment]
@smaldini I'm trying to track those changes. Were those included or merged in any way?
Is there another issue that I can follow to track this?

**Pull request closed without merging**
