### PR TITLE
[tests] Switch from deprecated Processors to Sinks

### PR DESCRIPTION
**Pull request by violetagg**

### CODE REVIEW

**Comment by violetagg** [comment]
@simonbasle PTAL

**Review by simonbasle — COMMENTED** [review]
looks good, although technically all these sinks could use the `Sinks.unsafe()` rootSpec. and in tests, it would also be ok to use `tryEmitNext(t).orThrow()`.

**Comment by violetagg** [comment]
> looks good, although technically all these sinks could use the `Sinks.unsafe()` rootSpec. and in tests, it would also be ok to use `tryEmitNext(t).orThrow()`.

For the rest of tests I agree but for `MonoSendManyTest` we cannot do that because we try to race between `cancel` and `emit`?

```
RaceTestUtils.race(testSubscriber::cancel, () -> {
	for (ByteBuf buf : buffersToSend) {
		source.tryEmitNext(buf).orThrow();
	}
});
```

```
reactor.core.publisher.Sinks$EmissionException: Sink emission failed with FAIL_CANCELLED
        at reactor.core.publisher.Sinks$EmitResult.orThrow(Sinks.java:174)
        at reactor.netty.channel.MonoSendManyTest.lambda$shouldNotLeakIfFusedOnRacingCancelAndOnNext$21(MonoSendManyTest.java:234)
```

**Comment by violetagg** [comment]
> looks good, although technically all these sinks could use the `Sinks.unsafe()` rootSpec. and in tests, it would also be ok to use `tryEmitNext(t).orThrow()`.

PTAL

**Review by simonbasle — APPROVED** [review]

**Pull request merged**
