### PR TITLE
fix #203: Introduce flush on each with event loop option.

### LINKED ISSUE #203: flush behavior
Currently there seems to be two modes for flushing. One is flushing on each write, and the other is flush at the end of stream. This lead two a couple problems. The first is a stream of data that doesn't end is never flushed, and the send is that you end up with a bunch of writes and flushes. I did some experimenting with RSocket, and came up with a good in-between solution. I was able to get roughly 15k more RPS with similar latency to writeAndFlush for a perf test we have. What I did was on each emit I attempted to schedule a flush - something along these lines:
```
// Code Writing to Netty
ChannelFuture write = channel.write(o);
if (!channel.isWritable()) {
  channel.flush();
} else {
    if (scheduledFlush == 0) {
      scheduleFlush(channel);
    }
}

return FutureMono.from(write);
...
// Method attempts to schedule a flush on the Netty event loop
void scheduleFlush(Channel channel) {
    if (SCHEDULED_FLUSH.compareAndSet(this, 0, 1)) {
      channel
          .eventLoop()
          .execute(
              () -> {
                channel.flush();
                SCHEDULED_FLUSH.set(ChannelOperationsHandler.this, 0);
              });
    }
  }
```
The SCHEDULED_FLUSH variable acted as a guard so if there was multiple writes at the same time flush was only called once.  I don't know if this is ideal for behavior for all scenarios but it seemed to work well for what I was doing.  It would be nice have something like this be an optional, or be able to plugin your own version of ChannelOperationsHandler so you could do custom implementations for your use case. Maybe there is a way to do that now, but it seemed like the ChannelOperationsHandler was created instead another class, and then handed 'this'

### PR DESCRIPTION
**Pull request by violetagg**

### CODE REVIEW

**Comment by robertroeser** [comment]
I took a look. There appears to be an infinite loop drain when I use out.send(). It just keeps decrementing the WIP counter, never exiting right here:
https://github.com/violetagg/reactor-netty/blob/e8691112f7f1dc71de570b669261e396eee7c736/src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java#L388

It worked for a few items when I commented out this block of code:
```
if (pendingWrites == null || innerActive || !ctx.channel()
				                                                .isWritable()) {
					if (!ctx.channel().isWritable() && hasPendingWriteBytes()) {
						ctx.flush();
					}
					if (WIP.decrementAndGet(this) == 0) {
						break;
					}
					continue;
				}
```

If I sent more than a few items through it looks up - I assume from filing up a buffer. I'll create a branch of RSocket that reproduces  this problem when I get a chance.

**Comment by robertroeser** [comment]
@violetagg @smaldini 

Here's a link to the RSocket code:
https://github.com/robertroeser/rsocket-java/blob/infiniteLoop/

If you run a request replay test in the TcpClientServerTest you will get an infinite loop. To see the implementation of the test look in the base class.

Here's the class connection class:
https://github.com/robertroeser/rsocket-java/blob/infiniteLoop/rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/NettyDuplexConnection.java

**Comment by violetagg** [comment]
I took a look at the code but it didn't seem to be a problem related to this change or you observed something else?
It didn't reach `doWrite` at all.

```
18:00:20,012 DEBUG [main] (Loggers.java) - Default epoll support : false
18:00:20,077 DEBUG [main] (Loggers.java) - Connecting new channel: AbstractBootstrap$PendingRegistrationPromise@351d0846(incomplete)
18:00:20,086 DEBUG [reactor-tcp-nio-1] (Slf4JLogger.java) - [id: 0x1e4faa88] REGISTERED
18:00:20,087 DEBUG [reactor-tcp-nio-1] (Slf4JLogger.java) - [id: 0x1e4faa88] BIND: localhost/127.0.0.1:0
18:00:20,136 DEBUG [reactor-tcp-nio-1] (Slf4JLogger.java) - [id: 0x1e4faa88, L:/127.0.0.1:62066] ACTIVE
18:00:20,154 DEBUG [main] (Loggers.java) - New tcp client pool for /127.0.0.1:62066
18:00:20,163 DEBUG [reactor-tcp-nio-5] (Loggers.java) - Created [id: 0x29f0bb35], now 1 active connections
18:00:20,164 DEBUG [main] (Loggers.java) - Acquiring existing channel from pool: DefaultPromise@436a4e4b(incomplete) SimpleChannelPool{activeConnections=1}
18:00:20,167 DEBUG [reactor-tcp-nio-5] (Loggers.java) - After pipeline DefaultChannelPipeline{(reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (SimpleChannelPool$1#0 = io.netty.channel.pool.SimpleChannelPool$1), (reactor.right.reactiveBridge = reactor.ipc.netty.channel.ChannelOperationsHandler)}
18:00:20,171 DEBUG [reactor-tcp-nio-5] (Slf4JLogger.java) - [id: 0x29f0bb35] REGISTERED
18:00:20,171 DEBUG [reactor-tcp-nio-5] (Slf4JLogger.java) - [id: 0x29f0bb35] CONNECT: /127.0.0.1:62066
18:00:20,177 DEBUG [reactor-tcp-nio-5] (Slf4JLogger.java) - [id: 0x29f0bb35, L:/127.0.0.1:62067 - R:/127.0.0.1:62066] ACTIVE
18:00:20,177 DEBUG [reactor-tcp-nio-5] (Loggers.java) - Acquired active channel: [id: 0x29f0bb35, L:/127.0.0.1:62067 - R:/127.0.0.1:62066]
18:00:20,178 DEBUG [reactor-tcp-nio-1] (Slf4JLogger.java) - [id: 0x1e4faa88, L:/127.0.0.1:62066] READ: [id: 0x14dd615e, L:/127.0.0.1:62066 - R:/127.0.0.1:62067]
18:00:20,178 DEBUG [reactor-tcp-nio-6] (Loggers.java) - After pipeline DefaultChannelPipeline{(reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (ServerContextHandler#0 = reactor.ipc.netty.channel.ServerContextHandler), (reactor.right.reactiveBridge = reactor.ipc.netty.channel.ChannelOperationsHandler)}
18:00:20,178 DEBUG [reactor-tcp-nio-6] (Slf4JLogger.java) - [id: 0x14dd615e, L:/127.0.0.1:62066 - R:/127.0.0.1:62067] REGISTERED
18:00:20,180 DEBUG [reactor-tcp-nio-6] (Slf4JLogger.java) - [id: 0x14dd615e, L:/127.0.0.1:62066 - R:/127.0.0.1:62067] ACTIVE
18:00:20,178 DEBUG [reactor-tcp-nio-1] (Slf4JLogger.java) - [id: 0x1e4faa88, L:/127.0.0.1:62066] READ COMPLETE
18:00:20,184 DEBUG [reactor-tcp-nio-6] (Loggers.java) - [Channel] [id: 0x14dd615e, L:/127.0.0.1:62066 - R:/127.0.0.1:62067] handler is being applied: io.rsocket.transport.netty.server.TcpServerTransport$$Lambda$16/198761306@4bf33bfb
18:00:20,184 DEBUG [reactor-tcp-nio-5] (Loggers.java) - [Channel] [id: 0x29f0bb35, L:/127.0.0.1:62067 - R:/127.0.0.1:62066] handler is being applied: io.rsocket.transport.netty.client.TcpClientTransport$$Lambda$38/889729797@2d650ef7
18:00:20,185 DEBUG [reactor-tcp-nio-6] (Slf4JLogger.java) - [id: 0x14dd615e, L:/127.0.0.1:62066 - R:/127.0.0.1:62067] USER_EVENT: reactor.ipc.netty.NettyPipeline$SendOptionsChangeEvent@38f66f98
18:00:20,185 DEBUG [reactor-tcp-nio-5] (Slf4JLogger.java) - [id: 0x29f0bb35, L:/127.0.0.1:62067 - R:/127.0.0.1:62066] USER_EVENT: reactor.ipc.netty.NettyPipeline$SendOptionsChangeEvent@6de72904
18:00:20,186 DEBUG [reactor-tcp-nio-6] (Loggers.java) - [id: 0x14dd615e, L:/127.0.0.1:62066 - R:/127.0.0.1:62067] New sending options
18:00:20,186 DEBUG [reactor-tcp-nio-5] (Loggers.java) - [id: 0x29f0bb35, L:/127.0.0.1:62067 - R:/127.0.0.1:62066] New sending options
18:00:20,191 DEBUG [reactor-tcp-nio-5] (Loggers.java) - Added decoder [client-length-codec] at the end of the user pipeline, full pipeline: [reactor.left.loggingHandler, client-length-codec, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
18:00:20,191 DEBUG [reactor-tcp-nio-6] (Loggers.java) - Added decoder [server-length-codec] at the end of the user pipeline, full pipeline: [reactor.left.loggingHandler, server-length-codec, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
18:00:20,203 DEBUG [reactor-tcp-nio-6] (Loggers.java) - [id: 0x14dd615e, L:/127.0.0.1:62066 - R:/127.0.0.1:62067] Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
18:00:20,217 DEBUG [reactor-tcp-nio-5] (Loggers.java) - [id: 0x29f0bb35, L:/127.0.0.1:62067 - R:/127.0.0.1:62066] Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
18:00:20,230 DEBUG [reactor-tcp-nio-5] (Loggers.java) - [id: 0x29f0bb35, L:/127.0.0.1:62067 - R:/127.0.0.1:62066] Writing object FluxLogFuseable
18:00:20,233  INFO [reactor-tcp-nio-5] (Loggers.java) - | onSubscribe([Fuseable] FluxMapFuseable.MapFuseableSubscriber)
18:00:20,234  INFO [reactor-tcp-nio-5] (Loggers.java) - | request(32)
18:00:20,247 DEBUG [reactor-tcp-nio-5] (Loggers.java) - [id: 0x29f0bb35, L:/127.0.0.1:62067 - R:/127.0.0.1:62066] Writing object FluxLogFuseable
18:00:20,252 DEBUG [reactor-tcp-nio-5] (Loggers.java) - [id: 0x29f0bb35, L:/127.0.0.1:62067 - R:/127.0.0.1:62066] Writing object FluxLogFuseable
```

**Comment by robertroeser** [comment]
@violetagg Yes - it didn't get that far - it seems to get suck in infinite loop in the drain method decrementing the WIP counter.

**Comment by violetagg** [comment]
> it seems to get suck in infinite loop in the drain method decrementing the WIP counter.

Let's continue this in another issue?

**Pull request merged**
