### PR TITLE
Bug in reactor.netty.tcp.SslProvider.SslReadHandler

### PR DESCRIPTION
**Pull request by kosmosimonyi**
Hope fix Bug in reactor.netty.tcp.SslProvider.SslReadHandler

### CODE REVIEW

**Comment by violetagg** [comment]
@kosmosimonyi Can you elaborate more on the use case?

**Comment by pivotal-issuemaster** [comment]
@kosmosimonyi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1537)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1537) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by kosmosimonyi** [comment]
> @kosmosimonyi Can you elaborate more on the use case?
> Do you manipulate the pipeline by yourself?

you mean I should write a example that can run?

**Comment by kosmosimonyi** [comment]
> @kosmosimonyi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1537)!
> 
> [Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1537) to manually synchronize the status of this Pull Request.
> 
> See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

sorry ,my bd,I will sumbit issue in next time. I don't pull request,I just illustrate a bug.

**Comment by kosmosimonyi** [comment]
> @kosmosimonyi Can you elaborate more on the use case?
> Do you manipulate the pipeline by yourself?

@violetagg I deveop a reactor MySQL dirver in new api(not R2DBC,I thaink R2DBC design not good) now.

**Comment by violetagg** [comment]
@kosmosimonyi Wdyt about closing this one and 
* Open an issue if there is Reactor Netty issue
* Or ask your questions on [Gitter](https://gitter.im/reactor/reactor-netty)

**Comment by kosmosimonyi** [comment]
> @kosmosimonyi Wdyt about closing this one and
> 
> * Open an issue if there is Reactor Netty issue
> * Or ask your questions on [Gitter](https://gitter.im/reactor/reactor-netty)

sorry,my bad,I open an issue .you clsoe this one please.

**Pull request closed without merging**
