### PR TITLE
Adapt to netty changes for CharsetUtil

### PR DESCRIPTION
**Pull request by pderop**
This PR adapts to the recent change made in the following Netty PR:

Remove Charset constants from CharsetUtil (https://github.com/netty/netty/pull/12741)

### CODE REVIEW

**Comment by pderop** [comment]
forced push, because a fix was missing in .github/workflows/check_transport.yml

**Comment by pderop** [comment]
forced push again, because a codec-haproxy PR is also needed from check_transport.yml

**Comment by pderop** [comment]
forced push again, because a codec-extra PR is also needed from check_transport.yml

**Comment by pderop** [comment]
@reactor/core-team ,

Can you review this PR please (it is for netty5 branch) ? 

it just adapts to some Netty changes that has been recently done:

- [#12741](https://github.com/netty/netty/pull/12741): io.netty5.util.CharsetUtil constants are not used anymore, and are replaced by standard constants from java.nio.charset.StandardCharsets (

- [#12739](https://github.com/netty/netty/pull/12739): io.netty5.buffer.api.internal.Statics has been renamed to io.netty5.buffer.api.internal.InternalBufferUtils

I also changed the .github/workflows/check_transport.yml in order to build agains the same kind of PRs which have been made for the codec (haproxy,extra,socks-proxy).

thanks !

**Review by chemicL — APPROVED** [review]
Remember to revert temporary changes in `.github/workflows/check_transport.yml`. Aside from that LGTM.

**Comment by pderop** [comment]
@chemicL , thanks for the review. I will revert the check_transport.yml when the netty contrib PRs will be merged.

**Pull request merged**
