### PR TITLE
Update Netty version to 4.1.41.Final

### PR DESCRIPTION
**Pull request by violetagg**
Adapt to a change in Netty connection pool
https://github.com/netty/netty/issues/9542

### CODE REVIEW

**Comment by violetagg** [comment]
#844 is still not resolved

**Comment by barclay-reg** [comment]
is there any chance to update directly to netty  4.1.42 ... needed to see https://github.com/netty/netty/issues/9571 included, as this exposes a security issue

**Comment by simonbasle** [comment]
(NB: as of today the UDP issue with epoll is still not resolved in `4.1.42.Final` nor in `4.1.43.Final-SNAPSHOT`)

**Comment by smaldini** [comment]
Looking at this fix I wonder abuot the AttributeKey - it feels like this is only checking if the key has been ever used in "any pool". I suspect the intent was to check if the pool key is currently set on the channel ?

**Pull request merged**
