### PR TITLE
Allow dots in parametrized path segments

### PR DESCRIPTION
**Pull request by mtritschler**
Fixes part of https://github.com/reactor/reactor-netty/issues/30

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mtritschler Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=31)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-netty&pullRequestId=31) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by smaldini** [comment]
Hey @mtritschler would you mind signing th cla so we get that in ?

**Comment by mtritschler** [comment]
@smaldini, sure. But I need to get approval from our legal department first... #thuglife
I have already reached out to them, answer still pending.

To speed things up; does this maybe fall into the "obvious fix" bucket?

**Comment by pivotal-issuemaster** [comment]
@mtritschler This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by simonbasle** [comment]
@mtritschler this is not an obvious fix (as described in the CLA tool's FAQ) unfortunately. But it look like simply putting the words in a PR comment marks the PR as obvious in the mind of the tool... Bad robot, bad 🤖 
:woman_judge: please continue spamming your legal department about the CLA :man_judge:

**Comment by smaldini** [comment]
Awesome, you are a true hero @mtritschler  🗡  - we'll look at the other problem about query parameters separately.

**Comment by smaldini** [comment]
I consider it an obvious fix for now, however its borderline due to the Regex change, we'll know for next time ;D However for further more advanced PR stuff we'll take a look.

**Comment by simonbasle** [comment]
@mtritschler despite that, if you can get to signing the CLA, that would be great ;)

**Pull request merged**
