### PR TITLE
With Java toolchain in place AllowRedefinitionToAddDeleteMethods is not needed

### PR DESCRIPTION
**Pull request by violetagg**
The exception below is thrown when Java version specified in the `PATH` is `> 8`

```
Unrecognized VM option 'AllowRedefinitionToAddDeleteMethods'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized VM option 'AllowRedefinitionToAddDeleteMethods'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Process 'Gradle Test Executor 159' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 159' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:414)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:141)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:42)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:94)
```

### CODE REVIEW

**Review by pderop — APPROVED** [review]
indeed, I have missed the problem because I have used java11 when testing previous PR.

LGTM

**Comment by violetagg** [comment]
@reactor/netty-team PTAL

**Comment by violetagg** [comment]
@pderop @simonbasle Thanks

**Pull request merged**
