### PR TITLE
Make metric tests faster

### PR DESCRIPTION
**Pull request by pderop**
This PR is an attempt to reduce metrics related test execution time.
For the moment it's just experimental, to see if CI tests are passing OK.

### CODE REVIEW

**Comment by violetagg** [comment]
@pderop Is it possible to apply the same fix for the other tests that do `sleep` before checking the metrics?

**Comment by pderop** [comment]
@violetagg, could you please look into the _PooledConnectionProviderDefaultMetricsTest.testConnectionPoolPendingAcquireSize_ test, because I tried to get rid of the remaining delay without any success ? thanks.

**Comment by violetagg** [comment]
> @violetagg, could you please look into the _PooledConnectionProviderDefaultMetricsTest.testConnectionPoolPendingAcquireSize_ test, because I tried to get rid of the remaining delay without any success ? thanks.

This will be handled in #2119

**Review by violetagg — APPROVED** [review]

**Comment by violetagg** [comment]
@simonbasle PTAL

**Review by simonbasle — APPROVED** [review]

**Comment by pderop** [comment]
@simonbasle , @violetagg , thanks for the review.

**Pull request merged**
