### PR TITLE
Use the new API Observation#parentObservation

### PR DESCRIPTION
**Pull request by violetagg**
Make context propagation optional dependency

### CODE REVIEW

**Review by marcingrzejszczak — APPROVED** [review]

**Review by pderop — APPROVED** [review]
LGTM

**Review by rstoyanchev — APPROVED** [review]
This makes more sense, avoiding the creation of a ThreadLocal. 

I know it's a separate question, but I was just wondering [is this](https://github.com/reactor/reactor-core/blob/5e9b08465f718352913f09f723b41ffae7e3f427/reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListener.java#L91) in reactor-core-micrometer a similar pattern that could also change?

**Comment by violetagg** [comment]
> This makes more sense, avoiding the creation of a ThreadLocal.
> 
> I know it's a separate question, but I was just wondering [is this](https://github.com/reactor/reactor-core/blob/5e9b08465f718352913f09f723b41ffae7e3f427/reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListener.java#L91) in reactor-core-micrometer a similar pattern that could also change?

Yes we can use the `parentObservation` directly in `reactor-core-micrometer` also. /cc @simonbasle

**Comment by violetagg** [comment]
@pderop @rstoyanchev @marcingrzejszczak Thanks for the review!

**Pull request merged**
