### PR TITLE
Build with Java 17

### PR DESCRIPTION
**Pull request by violetagg**
Reactor Netty integration with Netty 5 is based on Java 17
Netty 5 requires Java 11

### CODE REVIEW

**Comment by violetagg** [comment]
This PR depends on #2195

**Comment by pderop** [comment]
When trying to do "./gradlew check", I'm getting this error ?

```
Execution failed for task ':checkstyleNohttp'.
> Could not create service of type IsolatedAntBuilder using BuildScopeServices.createIsolatedAntBuilder().
   > Could not inspect the Groovy system for ClassLoader VisitableURLClassLoader(ant-and-gradle-loader)
```

**Comment by violetagg** [comment]
> When trying to do "./gradlew check", I'm getting this error ?
> 
> ```
> Execution failed for task ':checkstyleNohttp'.
> > Could not create service of type IsolatedAntBuilder using BuildScopeServices.createIsolatedAntBuilder().
>    > Could not inspect the Groovy system for ClassLoader VisitableURLClassLoader(ant-and-gradle-loader)
> ```

I don't see this issue neither on the CI nor locally. What's your OS and java version?

**Comment by pderop** [comment]
it's ok now, there were some remaining gradle daemons that have previously been launched using jdk8.
after having killed them, it's now ok.

**Review by pderop — APPROVED** [review]
LGTM

**Comment by violetagg** [comment]
This PR depends on #2198

**Review by simonbasle — CHANGES_REQUESTED** [review]
you'll need to also change the java version in other GHA workflows: `check_netty_snapshots.yml`, `publish.yml`

**Review by simonbasle — APPROVED** [review]

**Pull request merged**
