### PR TITLE
Update Micrometer dependencies to 1.10.0-SNAPSHOT before RC1

### PR DESCRIPTION
**Pull request by violetagg**
Update Micrometer Tracing dependency to version 1.0.0-SNAPSHOT
Update Micrometer Docs Generator dependency to version 1.0.0-SNAPSHOT
Update Context Propagation dependency to version 1.0.0-SNAPSHOT

### CODE REVIEW

**Comment by violetagg** [comment]
@shakuzen @marcingrzejszczak @jonatan-ivanov PTAL

**Review by marcingrzejszczak — APPROVED** [review]
LGTM!

**Review by shakuzen — APPROVED** [review]
LGTM

**Review by OlegDokuka — APPROVED** [review]

**Review by chemicL — APPROVED** [review]

**Review by jonatan-ivanov — APPROVED** [review]

**Comment by violetagg** [comment]
This is superseded by #2538

**Pull request merged**
