### PR TITLE
remove redundant hashmaps which lead to OOM

### PR DESCRIPTION
**Pull request by AntonGabov**
Fix of the issue https://github.com/reactor/reactor-netty/issues/866

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@AntonGabov Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=873)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-netty&pullRequestId=873) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by AntonGabov** [comment]
1) There is no need in these hashmaps as creation of `Matcher` is not expensive operation.
2) If there are millions of requests, synchronized on map can become a bottleneck

**Comment by smaldini** [comment]
Looks like a neat optimization - make sure you sign the cla and w'ere good.

**Comment by pivotal-issuemaster** [comment]
@AntonGabov Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=873)!

**Comment by smaldini** [comment]
Awesome ! Closed with https://github.com/reactor/reactor-netty/commit/fe6653fac44df16664bdd0628ad56cd142175bca

**Pull request closed without merging**
