### PR TITLE
Introducing HTTP3 support 

### PR DESCRIPTION
**Pull request by fokion**
Started reviewing and migrating parts

### CODE REVIEW

**Comment by violetagg** [comment]
@fokion May be It is good if you can share what are the overall plans/architecture that you have in mind.

We can use this project https://github.com/netty/netty-incubator-codec-http3

**Comment by fokion** [comment]
The reason why I added this draft pr is to share my thoughts. 

Are we going to add the dependency as it is or migrate it to this project? Moreover there are some updates since it was last implemented in that incubator.

**Comment by violetagg** [comment]
We would like to use `netty-incubator-codec-http3` as a dependency, yes. If something is missing from SPEC point of view, we prefer to contribute it to `netty-incubator-codec-http3`.

**Comment by fokion** [comment]
Ok in that case will add the dependency directly later today and raise any PRs there. Thanks for the clarification

**Comment by violetagg** [comment]
This is superseded by #2972

**Pull request closed without merging**
