### PR TITLE
Fix cross-site scripting vulnerability in test

### PR DESCRIPTION
**Pull request by pderop**
Fix cross-site scripting (XSS) vulnerability github security alert in the TomcatServer class.

See https://github.com/reactor/reactor-netty/security/code-scanning/9

### CODE REVIEW

**Comment by pderop** [comment]
There is one failing test, it's not caused by this PR, but by the test from #2864, which has a bug. I will create a separate PR which will complement #2864.

I'm restarting the CI for the ubuntu-20.04 native checks ...

**Comment by pderop** [comment]
The CI now constantly fails.
I will make the other PR now in order to fix the flaky test, and once it will be merged, I'll rebase this one on top of it.

**Comment by violetagg** [comment]
@pderop Please rebase this one

**Comment by pderop** [comment]
@violetagg , done, I have rebased it.

**Review by violetagg — APPROVED** [review]

**Pull request merged**
