### PR TITLE
Adapt to the changes in Netty 5.0.0.Alpha5-SNAPSHOT

### PR DESCRIPTION
**Pull request by violetagg**

### CODE REVIEW

**Comment by violetagg** [comment]
Wait with the review I need to check why UDS tests with HTTP (with TCP and UDP they are OK) are not passing on Linux

**Comment by violetagg** [comment]
> Wait with the review I need to check why UDS tests with HTTP (with TCP and UDP they are OK) are not passing on Linux with native transport

It was a test problem, now it should be ok

**Comment by violetagg** [comment]
the failed tests on Windows CI are flaky and known and there are issues for them

**Review by simonbasle — COMMENTED** [review]
reviewed up to `UDS: Channel#localAddress/remoteAddress are available only when NIO transport`, LGTM 👍

**Review by simonbasle — APPROVED** [review]

**Comment by violetagg** [comment]
@simonbasle Thanks for the review!

**Pull request merged**
